"""setup database v2

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-28 15:12:58.374790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('api_url', sa.Text(), nullable=False),
    sa.Column('api_token', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partners')),
    sa.UniqueConstraint('code', name=op.f('uq_partners_code'))
    )
    op.create_table('permission_groups',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_permission_groups_name'))
    )
    op.create_table('provinces',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_provinces'))
    )
    op.create_table('districts',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('province_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['province_code'], ['provinces.code'], name=op.f('fk_districts_province_code_provinces')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_districts'))
    )
    op.create_table('partner_tariffs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('partner_id', sa.Integer(), nullable=False),
    sa.Column('service_name', sa.Text(), nullable=False),
    sa.Column('route_type', sa.Text(), nullable=False),
    sa.Column('base_fee', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.CheckConstraint('base_fee >= 0', name=op.f('ck_partner_tariffs_ck_partner_tariffs_base_fee')),
    sa.ForeignKeyConstraint(['partner_id'], ['partners.id'], name=op.f('fk_partner_tariffs_partner_id_partners'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_tariffs'))
    )
    op.create_table('permission_actions',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['permission_groups.id'], name=op.f('fk_permission_actions_group_id_permission_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'action', name=op.f('pk_permission_actions'))
    )
    op.create_table('wards',
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_en', sa.Text(), nullable=True),
    sa.Column('district_code', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['district_code'], ['districts.code'], name=op.f('fk_wards_district_code_districts')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_wards'))
    )
    op.create_table('depots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.Column('address_detail', sa.Text(), nullable=False),
    sa.Column('ward_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ward_code'], ['wards.code'], name=op.f('fk_depots_ward_code_wards')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depots')),
    sa.UniqueConstraint('code', name=op.f('uq_depots_code'))
    )
    op.create_table('cod_handovers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('shipper_id', sa.Integer(), nullable=False),
    sa.Column('cashier_id', sa.Integer(), nullable=True),
    sa.Column('total_cod_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('actual_received_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'approved', 'rejected')", name=op.f('ck_cod_handovers_ck_cod_handovers_status')),
    sa.CheckConstraint('actual_received_amount IS NULL OR actual_received_amount >= 0', name=op.f('ck_cod_handovers_ck_cod_handovers_actual_amount')),
    sa.CheckConstraint('total_cod_amount >= 0', name=op.f('ck_cod_handovers_ck_cod_handovers_total_amount')),
    sa.ForeignKeyConstraint(['cashier_id'], ['users.id'], name=op.f('fk_cod_handovers_cashier_id_users')),
    sa.ForeignKeyConstraint(['shipper_id'], ['users.id'], name=op.f('fk_cod_handovers_shipper_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cod_handovers')),
    sa.UniqueConstraint('code', name=op.f('uq_cod_handovers_code'))
    )
    op.create_table('depot_ledgers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('depot_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('reference_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("transaction_type IN ('cod_collection', 'cod_payout', 'shipper_remittance', 'deposit', 'expense')", name=op.f('ck_depot_ledgers_ck_depot_ledgers_type')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_depot_ledgers_created_by_users')),
    sa.ForeignKeyConstraint(['depot_id'], ['depots.id'], name=op.f('fk_depot_ledgers_depot_id_depots')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_depot_ledgers'))
    )
    op.create_table('user_permission_groups',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['permission_groups.id'], name=op.f('fk_user_permission_groups_group_id_permission_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_permission_groups_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'group_id', name=op.f('pk_user_permission_groups'))
    )
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('license_plate', sa.Text(), nullable=False),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('max_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('max_volume_m3', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('latest_depot_id', sa.Integer(), nullable=True),
    sa.Column('latest_linehaul_id', sa.Integer(), nullable=True),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('active', 'inactive', 'maintenance')", name=op.f('ck_vehicles_ck_vehicles_status')),
    sa.CheckConstraint("vehicle_type IN ('motorcycle', 'truck')", name=op.f('ck_vehicles_ck_vehicles_type')),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_vehicles_driver_id_users')),
    sa.ForeignKeyConstraint(['latest_depot_id'], ['depots.id'], name=op.f('fk_vehicles_latest_depot_id_depots')),
    sa.ForeignKeyConstraint(['latest_linehaul_id'], ['linehauls.id'], name='fk_vehicles_latest_linehaul_id', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vehicles')),
    sa.UniqueConstraint('license_plate', name=op.f('uq_vehicles_license_plate'))
    )
    op.create_table('bill_status_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('latest_linehaul_id', sa.BigInteger(), nullable=True),
    sa.Column('latest_depot_id', sa.BigInteger(), nullable=True),
    sa.Column('changed_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_status_logs_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name=op.f('fk_bill_status_logs_changed_by_users')),
    sa.ForeignKeyConstraint(['latest_depot_id'], ['depots.id'], name=op.f('fk_bill_status_logs_latest_depot_id_depots')),
    sa.ForeignKeyConstraint(['latest_linehaul_id'], ['linehauls.id'], name='fk_bill_status_events_latest_linehaul_id', use_alter=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_status_logs'))
    )
    op.create_table('cod_handover_items',
    sa.Column('handover_id', sa.Integer(), nullable=False),
    sa.Column('bill_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_cod_handover_items_bill_id_bills'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['handover_id'], ['cod_handovers.id'], name=op.f('fk_cod_handover_items_handover_id_cod_handovers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('handover_id', 'bill_id', name=op.f('pk_cod_handover_items')),
    sa.UniqueConstraint('bill_id', name=op.f('uq_cod_handover_items_bill_id'))
    )
    op.create_table('linehauls',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('origin_depot_id', sa.Integer(), nullable=False),
    sa.Column('destination_depot_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('start_odometer', sa.Integer(), nullable=True),
    sa.Column('end_odometer', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('scheduled', 'loading', 'in_transit', 'arrived', 'completed')", name=op.f('ck_linehauls_ck_linehauls_status')),
    sa.ForeignKeyConstraint(['destination_depot_id'], ['depots.id'], name=op.f('fk_linehauls_destination_depot_id_depots')),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], name=op.f('fk_linehauls_driver_id_users')),
    sa.ForeignKeyConstraint(['origin_depot_id'], ['depots.id'], name=op.f('fk_linehauls_origin_depot_id_depots')),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], name=op.f('fk_linehauls_vehicle_id_vehicles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_linehauls')),
    sa.UniqueConstraint('code', name=op.f('uq_linehauls_code'))
    )
    op.drop_index(op.f('idx_bill_status_events_bill'), table_name='bill_status_events')
    op.drop_table('bill_status_events')
    op.alter_column('audit_events', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('audit_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_audit_events_entity'), table_name='audit_events')
    op.drop_constraint(op.f('uq_bill_content_lines_bill_line'), 'bill_content_lines', type_='unique')
    op.add_column('bills', sa.Column('sender_id', sa.Integer(), nullable=False))
    op.add_column('bills', sa.Column('receiver_id', sa.Integer(), nullable=False))
    op.add_column('bills', sa.Column('actual_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False))
    op.add_column('bills', sa.Column('chargeable_weight_kg', sa.Numeric(precision=12, scale=3), nullable=False))
    op.add_column('bills', sa.Column('is_insurance_required', sa.Boolean(), nullable=False))
    op.add_column('bills', sa.Column('cod_amount', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('bills', sa.Column('fee_insurance', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('bills', sa.Column('fee_other', sa.Numeric(precision=14, scale=2), nullable=False))
    op.add_column('bills', sa.Column('origin_depot_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('destination_depot_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('latest_depot_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('latest_linehaul_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('shipper_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('partner_id', sa.Integer(), nullable=True))
    op.add_column('bills', sa.Column('partner_bill_code', sa.Text(), nullable=True))
    op.alter_column('bills', 'cargo_type',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bills', 'service_tier_code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bills', 'payer',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('bills', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'da_tao'::text"))
    op.alter_column('bills', 'delivered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('bills', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bills', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bills', 'last_printed_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('idx_bills_customer_code'), table_name='bills')
    op.drop_index(op.f('idx_bills_receiver_phone'), table_name='bills')
    op.drop_index(op.f('idx_bills_search_receiver_address'), table_name='bills', postgresql_ops={'f_unaccent(lower(receiver_address))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_bills_search_receiver_name'), table_name='bills', postgresql_ops={'f_unaccent(lower(receiver_name))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_bills_search_sender_address'), table_name='bills', postgresql_ops={'f_unaccent(lower(sender_address))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_bills_search_sender_name'), table_name='bills', postgresql_ops={'f_unaccent(lower(sender_name))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('idx_bills_sender_phone'), table_name='bills')
    op.drop_index(op.f('idx_bills_status_created_at'), table_name='bills')
    op.drop_constraint(op.f('fk_bills_customer_id_customers'), 'bills', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bills_partner_id_partners'), 'bills', 'partners', ['partner_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_shipper_id_users'), 'bills', 'users', ['shipper_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_origin_depot_id_depots'), 'bills', 'depots', ['origin_depot_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_receiver_id_customers'), 'bills', 'customers', ['receiver_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_destination_depot_id_depots'), 'bills', 'depots', ['destination_depot_id'], ['id'])
    op.create_foreign_key('fk_bills_latest_linehaul_id', 'bills', 'linehauls', ['latest_linehaul_id'], ['id'], use_alter=True)
    op.create_foreign_key(op.f('fk_bills_sender_id_customers'), 'bills', 'customers', ['sender_id'], ['id'])
    op.create_foreign_key(op.f('fk_bills_latest_depot_id_depots'), 'bills', 'depots', ['latest_depot_id'], ['id'])
    op.drop_column('bills', 'receiver_name')
    op.drop_column('bills', 'sender_address')
    op.drop_column('bills', 'customer_id')
    op.drop_column('bills', 'fee_other_surcharge')
    op.drop_column('bills', 'customer_code')
    op.drop_column('bills', 'sender_province')
    op.drop_column('bills', 'fee_fuel_surcharge')
    op.drop_column('bills', 'receiver_address')
    op.drop_column('bills', 'sender_name')
    op.drop_column('bills', 'receiver_district')
    op.drop_column('bills', 'receiver_province')
    op.drop_column('bills', 'receiver_phone')
    op.drop_column('bills', 'sender_district')
    op.drop_column('bills', 'sender_phone')
    op.add_column('customers', sa.Column('code', sa.String(), nullable=True))
    op.add_column('customers', sa.Column('name', sa.Text(), nullable=False))
    op.add_column('customers', sa.Column('customer_type', sa.String(), nullable=False))
    op.add_column('customers', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('customers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customers', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('idx_customers_phone'), table_name='customers')
    op.drop_index(op.f('idx_customers_search_name'), table_name='customers', postgresql_ops={'f_unaccent(lower(display_name))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('uq_customers_customer_code'), 'customers', type_='unique')
    op.create_unique_constraint(op.f('uq_customers_code'), 'customers', ['code'])
    op.drop_column('customers', 'province')
    op.drop_column('customers', 'customer_code')
    op.drop_column('customers', 'display_name')
    op.drop_column('customers', 'district')
    op.drop_column('customers', 'address')
    op.alter_column('service_tiers', 'code',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('service_tiers', 'scope',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('users', sa.Column('depot_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('users', 'username',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False,
               existing_server_default=sa.text("'staff'::text"))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_unique_constraint(op.f('uq_users_phone'), 'users', ['phone'])
    op.create_foreign_key(op.f('fk_users_depot_id_depots'), 'users', 'depots', ['depot_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_users_depot_id_depots'), 'users', type_='foreignkey')
    op.drop_constraint(op.f('uq_users_phone'), 'users', type_='unique')
    op.alter_column('users', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'role',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'staff'::text"))
    op.alter_column('users', 'username',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('users', 'depot_id')
    op.drop_column('users', 'metadata')
    op.drop_column('users', 'phone')
    op.alter_column('service_tiers', 'scope',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('service_tiers', 'code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.add_column('customers', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('district', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('customers', sa.Column('display_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('customer_code', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('customers', sa.Column('province', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(op.f('uq_customers_code'), 'customers', type_='unique')
    op.create_unique_constraint(op.f('uq_customers_customer_code'), 'customers', ['customer_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_customers_search_name'), 'customers', [sa.literal_column('f_unaccent(lower(display_name))')], unique=False, postgresql_ops={'f_unaccent(lower(display_name))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_customers_phone'), 'customers', ['phone'], unique=False)
    op.alter_column('customers', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('customers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('customers', 'metadata')
    op.drop_column('customers', 'customer_type')
    op.drop_column('customers', 'name')
    op.drop_column('customers', 'code')
    op.add_column('bills', sa.Column('sender_phone', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('sender_district', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('receiver_phone', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('receiver_province', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('receiver_district', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('sender_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('receiver_address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('fee_fuel_surcharge', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('sender_province', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('customer_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('bills', sa.Column('fee_other_surcharge', sa.NUMERIC(precision=14, scale=2), server_default=sa.text("'0'::numeric"), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('customer_id', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('bills', sa.Column('sender_address', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('bills', sa.Column('receiver_name', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('fk_bills_latest_depot_id_depots'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_sender_id_customers'), 'bills', type_='foreignkey')
    op.drop_constraint('fk_bills_latest_linehaul_id', 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_destination_depot_id_depots'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_receiver_id_customers'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_origin_depot_id_depots'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_shipper_id_users'), 'bills', type_='foreignkey')
    op.drop_constraint(op.f('fk_bills_partner_id_partners'), 'bills', type_='foreignkey')
    op.create_foreign_key(op.f('fk_bills_customer_id_customers'), 'bills', 'customers', ['customer_id'], ['id'])
    op.create_index(op.f('idx_bills_status_created_at'), 'bills', ['status', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_bills_sender_phone'), 'bills', ['sender_phone'], unique=False)
    op.create_index(op.f('idx_bills_search_sender_name'), 'bills', [sa.literal_column('f_unaccent(lower(sender_name))')], unique=False, postgresql_ops={'f_unaccent(lower(sender_name))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_bills_search_sender_address'), 'bills', [sa.literal_column('f_unaccent(lower(sender_address))')], unique=False, postgresql_ops={'f_unaccent(lower(sender_address))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_bills_search_receiver_name'), 'bills', [sa.literal_column('f_unaccent(lower(receiver_name))')], unique=False, postgresql_ops={'f_unaccent(lower(receiver_name))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_bills_search_receiver_address'), 'bills', [sa.literal_column('f_unaccent(lower(receiver_address))')], unique=False, postgresql_ops={'f_unaccent(lower(receiver_address))': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('idx_bills_receiver_phone'), 'bills', ['receiver_phone'], unique=False)
    op.create_index(op.f('idx_bills_customer_code'), 'bills', ['customer_code'], unique=False)
    op.alter_column('bills', 'last_printed_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bills', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bills', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('bills', 'delivered_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('bills', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'da_tao'::text"))
    op.alter_column('bills', 'payer',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bills', 'service_tier_code',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('bills', 'cargo_type',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('bills', 'partner_bill_code')
    op.drop_column('bills', 'partner_id')
    op.drop_column('bills', 'shipper_id')
    op.drop_column('bills', 'latest_linehaul_id')
    op.drop_column('bills', 'latest_depot_id')
    op.drop_column('bills', 'destination_depot_id')
    op.drop_column('bills', 'origin_depot_id')
    op.drop_column('bills', 'fee_other')
    op.drop_column('bills', 'fee_insurance')
    op.drop_column('bills', 'cod_amount')
    op.drop_column('bills', 'is_insurance_required')
    op.drop_column('bills', 'chargeable_weight_kg')
    op.drop_column('bills', 'actual_weight_kg')
    op.drop_column('bills', 'receiver_id')
    op.drop_column('bills', 'sender_id')
    op.create_unique_constraint(op.f('uq_bill_content_lines_bill_line'), 'bill_content_lines', ['bill_id', 'line_no'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_audit_events_entity'), 'audit_events', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.alter_column('audit_events', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('audit_events', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.create_table('bill_status_events',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('bill_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('from_status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('to_status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('actor_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_bill_status_events_actor_id_users')),
    sa.ForeignKeyConstraint(['bill_id'], ['bills.id'], name=op.f('fk_bill_status_events_bill_id_bills'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bill_status_events'))
    )
    op.create_index(op.f('idx_bill_status_events_bill'), 'bill_status_events', ['bill_id', 'created_at'], unique=False)
    op.drop_table('linehauls')
    op.drop_table('cod_handover_items')
    op.drop_table('bill_status_logs')
    op.drop_table('vehicles')
    op.drop_table('user_permission_groups')
    op.drop_table('depot_ledgers')
    op.drop_table('cod_handovers')
    op.drop_table('depots')
    op.drop_table('wards')
    op.drop_table('permission_actions')
    op.drop_table('partner_tariffs')
    op.drop_table('districts')
    op.drop_table('provinces')
    op.drop_table('permission_groups')
    op.drop_table('partners')
    # ### end Alembic commands ###
